# Generated by Django 6.0.5 on 2026-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_agregado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]

