# Generated by Django 6.0.5 on 2026-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_fecha_agregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(default='cat_videojuegos.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='prod_zelda.png', max_length=200),
        ),
    ]

